// Copyright © 2026 Jalapeno Labs

/**
 * Copies the generated protobuf contract into the package.
 *
 * `gen/ts` at the repository root is the one source of truth for the contract,
 * regenerated by `buf generate` and committed. It sits outside this package, and
 * npm can only publish files beneath a package directory, so the published
 * tarball has to carry its own copy. This is the same constraint that forces the
 * Rust output to land inside `arsox-sdk` rather than under `gen/`.
 *
 * Copying rather than committing a second copy keeps `gen/ts` the only checked-in
 * generated tree, so the contract can never be current in one place and stale in
 * the other. `src/proto` is git ignored and rebuilt on every build, typecheck,
 * and test run.
 *
 * The generated files are emitted with `import_extension=.js`, which is exactly
 * what this package's ESM + NodeNext resolution wants, so they compile in place
 * with no rewriting.
 */

import { cp, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const source = join(packageRoot, '..', '..', 'gen', 'ts', 'arsox')
const destination = join(packageRoot, 'src', 'proto', 'arsox')

// Removed first rather than copied over, so a message deleted upstream does not
// linger here and keep compiling.
await rm(destination, { recursive: true, force: true })
await cp(source, destination, { recursive: true })

console.log(`synced the protobuf contract into ${destination}`)
