// Copyright © 2026 Jalapeno Labs

//! Thread workspaces on disk.
//!
//! Every thread owns one subtree of the workspace root, named for the thread.
//! Creating it is the runner's job, because it happens on the way to spawning a
//! harness. Removing it is the collector's, because it happens long after
//! anything is running.

use std::path::{Path, PathBuf};

/// The directory a thread owns.
///
/// # Errors
///
/// Returns [`WorkspaceError::UnsafeThreadId`] when the id is not a plain UUID.
///
/// Thread ids are generated by the satellite and never accepted from a client,
/// so this cannot fire today. It is checked anyway: the id becomes a filesystem
/// path, and the day something else supplies one, a traversal here would reach
/// the whole volume. The cost of the check is a character scan.
pub fn thread_directory(root: &Path, thread_id: &str) -> Result<PathBuf, WorkspaceError> {
    let safe = thread_id.len() == 36
        && thread_id
            .chars()
            .all(|character| character.is_ascii_hexdigit() || character == '-');

    if !safe {
        return Err(WorkspaceError::UnsafeThreadId(thread_id.to_owned()));
    }

    Ok(root.join(thread_id))
}

/// Removes a thread's subtree, including anything not downloaded from it.
///
/// A workspace that is already gone is a success rather than an error. The
/// collector runs on an interval and a thread can be collected by more than one
/// path, so "already removed" is a normal outcome and not worth an incident.
///
/// # Errors
///
/// Returns [`WorkspaceError::UnsafeThreadId`] for an id that is not a plain
/// UUID, and [`WorkspaceError::Remove`] when the subtree exists and cannot be
/// removed.
pub async fn remove_thread_directory(root: &Path, thread_id: &str) -> Result<(), WorkspaceError> {
    let directory = thread_directory(root, thread_id)?;

    match tokio::fs::remove_dir_all(&directory).await {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(WorkspaceError::Remove {
            path: directory,
            source: error,
        }),
    }
}

#[derive(Debug, thiserror::Error)]
pub enum WorkspaceError {
    #[error("thread id {0} is not safe to use as a path")]
    UnsafeThreadId(String),

    #[error("could not remove {path}")]
    Remove {
        path: PathBuf,
        source: std::io::Error,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_thread_directory_is_named_for_its_thread() {
        let directory = thread_directory(
            Path::new("/workspace"),
            "019fd32f-a25f-7611-a4fe-c93cc2a6d782",
        )
        .expect("a UUID is safe");

        assert!(directory.ends_with("019fd32f-a25f-7611-a4fe-c93cc2a6d782"));
    }

    #[test]
    fn an_id_that_could_escape_the_root_is_refused() {
        // None of these can reach the satellite today. The check exists so that
        // stops being load-bearing.
        for hostile in [
            "../../etc",
            "..",
            "/etc/passwd",
            "019fd32f-a25f-7611-a4fe-c93cc2a6d78/..",
        ] {
            assert!(
                thread_directory(Path::new("/workspace"), hostile).is_err(),
                "{hostile} should be refused"
            );
        }
    }

    #[tokio::test]
    async fn removing_a_workspace_that_is_already_gone_succeeds() {
        // The collector runs on an interval and a thread can be collected by
        // more than one path, so this is a normal outcome.
        let root = std::env::temp_dir();
        remove_thread_directory(&root, "019fd32f-0000-7000-8000-000000000000")
            .await
            .expect("a workspace that is already gone is not an error");
    }

    #[tokio::test]
    async fn removing_a_workspace_takes_its_contents_with_it() {
        let root = std::env::temp_dir().join(format!("arsox-workspace-{}", std::process::id()));
        let thread_id = "019fd32f-1111-7111-8111-111111111111";
        let directory = thread_directory(&root, thread_id).expect("safe");

        tokio::fs::create_dir_all(directory.join("repos/api"))
            .await
            .expect("should create");
        tokio::fs::write(directory.join("repos/api/file.txt"), b"work")
            .await
            .expect("should write");

        remove_thread_directory(&root, thread_id)
            .await
            .expect("should remove");

        assert!(!directory.exists());
        let _ignored = tokio::fs::remove_dir_all(&root).await;
    }
}
