// Copyright © 2026 Jalapeno Labs

//! Rust client and protobuf contract for Arsox satellites.
//!
//! Arsox runs a fleet of self-hosted agent workers. Claude and Codex emit
//! different events with different shapes; a satellite normalizes both into the
//! single contract exposed here, so an application is written once and never
//! rewritten when the harness, model, or provider changes.
//!
//! # Layout
//!
//! [`proto`] holds the generated contract, mirroring the package tree under
//! `proto/` in the repository: `proto::thread::v1::Thread`,
//! `proto::event::v1::ThreadEvent`, and so on. These are the wire types. They
//! are generated at build time by `buf` and committed, so building this crate
//! never requires `protoc`.
//!
//! # Features
//!
//! `client` is enabled by default and carries the HTTP and WebSocket client. A
//! satellite depends on this crate with `default-features = false` to reach the
//! contract types without linking a client it will never call.
//!
//! # Examples
//!
//! ```
//! use arsox_sdk::proto::usage::v1::TokenUsage;
//!
//! // Absent is not zero: a harness that reports no cache accounting leaves
//! // these `None` rather than setting them to 0, so a cost reconciliation can
//! // tell "not reported" from "read nothing from cache".
//! let usage = TokenUsage::default();
//! assert_eq!(usage.cache_read_tokens, None);
//! ```

// Named `generated` rather than `gen`, which edition 2024 reserves as a
// keyword for generator blocks.
// `restriction` is allowed alongside the usual groups because the contract
// deliberately contains empty messages. `Unlimited`, `MirrorLength`, and
// `Declined` carry no fields on purpose: they make "no ceiling", "mirror the
// length", and "declined to answer" explicit cases rather than sentinel values.
// prost renders them as `struct Unlimited {}`, which no amount of care in the
// .proto can change.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    reason = "generated by prost through buf; regenerate rather than edit"
)]
mod generated;

pub mod helpers;

#[doc(inline)]
pub use generated::arsox as proto;
